/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */

import type { Metadata } from "next";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import { Inter, Reem_Kufi, Roboto, Zen_Kaku_Gothic_Antique } from "next/font/google";

const reemKufi = Reem_Kufi({ subsets: ['latin'] })
const zen = Zen_Kaku_Gothic_Antique(
  {
    subsets: ['latin'],
    weight: ["300", "400", "500", "700", "900"]
  }
)
const roboto = Roboto({
  subsets: ['latin'],
  weight: ["100", "300", "400", "500", "700", "900"]

})

const useFont = roboto

export const metadata: Metadata = {
  title: "Aminote | Create note effortlessly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
      <body className={`${useFont.className}`}>
        <ChakraProvider >

          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
