
import type { Metadata } from "next";
import { Inter, Reem_Kufi } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import theme from "./_theme/theme";

const reemKufi = Reem_Kufi({subsets: ['latin']})


export const metadata: Metadata = {
  title: "Aminote | Create note effortlessly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
      <body className={`${reemKufi.className}`}>
        <ChakraProvider >
          
        {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
